### PR TITLE
Control/Ardupilot: Proper handling of ArduCopter Height

### PR DESCRIPTION
**Pull request by krisklau**
This PR uses the right fields from mavlink to set Height, and also sets the altitude field in EstimatedState. 

The altitude is now used for medium-detection. The previous way it was done was not really valid. (NB: In Monitors/Medium; the altitude value is only used for copter. FW checks airspeed).

### CODE REVIEW

**Comment by krisklau** [comment]
Me and @jffortuna: OK. Will be merged.

**Comment by paulosousadias** [comment]
Wasn't Maria checking this? I have the impression she has something to say/do on this. @Maria can you confirm?

**Comment by krisklau** [comment]
Any updates, @mariacosta?

**Comment by mariacosta** [comment]
Hi,

Last week I spoke with João Fortuna on gtalk and I mentioned that this PR
could be merged already.

I didn't do the merge myself at the time as I understood Fortuna would do
it. Maybe I got it wrong..!
Let me know if you want me to do the merge.


Best regards,
Maria Costa

2016-05-05 22:11 GMT+01:00 krisklau <notifications@github.com>:

**Pull request merged**
