### PR TITLE
Feature/success print

### PR DESCRIPTION
**Pull request by mortenfyhn**
What do you think of this? It makes it possible to call `success()` from a task to get a green-colored console printout, which I think can be useful for stuff such as `successfully initialized with <some key parameters>`. It looks like this:

success

I'm opening a parallel pull request on the IMC repo: https://github.com/LSTS/imc/pull/22

### CODE REVIEW

**Comment by krisklau** [comment]
I like the greens! It adds another tool for the developers at first, and and then we can see how it can/should be adapted.

**Comment by mortenfyhn** [comment]
Yeah, "success" and green color might not be the best. What I'm aiming for is more "this piece of info is extra important, but it's not a warning/error", so maybe a "important" log option in blue color is better?

**Comment by tsmarques** [comment]
I like "important" or even "notification/notify" and I think the green colour is fitting for it.

**Comment by mortenfyhn** [comment]
Thanks! I'm looking forward to the feedback.

**Comment by tsmarques** [comment]
Hi,

sorry for the delayed feedback.
We've discussed this internally and see no problem in having another log level, called notification. Nonetheless we think this PR needs some changes:

- Revert the commit with IMC changes and do this on a separate PR on the [IMC](https://github.com/LSTS/imc) repository; Besides we think that the new enum value on `LogEntry` should follow `LBET_INFO` to maintain the logical order of the values;

After this we'll include the changes on a new IMC release we're planning for, on a separate branch.

Thanks,
Tiago

**Comment by mortenfyhn** [comment]
Closing this as I'm no longer developing on DUNE.

**Pull request closed without merging**
