### PR TITLE
Feature/quaternion

### PR DESCRIPTION
**Pull request by mortenfyhn**
Hey guys, thanks for doing all those merges recently. I've started working on a quaternion library. There is probably more work to be done, but I wanted to open a PR now to let you have an early look. (I'm aware that some of your coding guidelines aren't followed here, such as method documentation in header files, and newline after return value types. That can be fixed.) There is already some quaternion functionality inside DUNE's matrix class, but for more advanced usage I believe a separate quaternion class is appropriate.

A brief summary of the library in its current state:
* Quaternions are internally represented with a `DUNE::Math::Matrix`.
* Using the hamiltonian convention (w + ix + jy + kz) and vector representation [w, x, y, z] (real element first).
* Contains, among others, methods to set identity, get the internal matrix, calculate the norm, normalize the quaternion, and get the corresponding rotation matrix.
* Overloads most relevant operators, most notably quaternion product as well as quaternion and matrix products `quat * matrix` and `matrix * quat`.
* I have also added a separate class for Euler angles following the ZYX convention, to make it easier to convert to/from euler angles without making mistakes. Both classes have constructors that take an instance of the opposite class and converts it, to provide quaternion to euler and euler to quaternion functionality.
* I've also written tests.

Let me know what you think!

### CODE REVIEW

**Comment by mortenfyhn** [comment]
I think I accidentally hit the close button.

**Comment by oysstu** [comment]
Looks good. On the naming of EulerAnglesZyx; are we likely to use any other convention for the Euler angles? I'm for just naming it EulerAngles. It can be subclassed later if the need arises to implement different conventions.

**Comment by mortenfyhn** [comment]
That's a good point. On one hand, I don't see myself using anything else than ZYX, but on the other hand other people exist. Matlab uses ZYX as the default, and also supports ZYZ and XYZ for its conversions between Euler and quat.

You're thinking something like `class EulerAnglesZyx : public EulerAngles`?

**Comment by oysstu** [comment]
That was the thought. Another possibility is using a template with enum parameters specifying axes. The defaults can be ZYX. Both approaches saves for example implementing the ostream operator for every convention manually. 

```c++
enum class Axis {X, Y, Z};

template<Axis A = Axis::Z, Axis B = Axis::Y, Axis C = Axis::X>
class EulerAngles {
public:
    EulerAngles(int _a, int _b, int _c)
     : a(_a), b(_b), c(_c) {}
     int a, b, c;
};
```
Pretty sure the conversion can then be made generic using template shenanigans. For now, a template specialization for ZYX can be sufficient until someone gets around to it. I don't know, perhaps this is a case of overengineering =)

**Comment by mortenfyhn** [comment]
I'm not super confident with templates, but would that approach make it possible to instantiate any sort of Euler angles? How do you differentiate between the conventions that are valid and implemented, and those that are invalid (say 'ZZZ') or unimplemented?

Regardless of that, I think I prefer the arguably simpler inheritance-based way. Then you also get that you can't instantiate, say, a `EulerAnglesZzz` because it doesn't exist.

**Comment by oysstu** [comment]
Templates can be a pain, and is not necessarily the correct approach. As you say, it might be best to use a simple inheritance. Templates makes sense if the goal is to eventually support all conventions, as it might be possible to implement it once for all combinations.

This would be one way to ensure that non-ZYX conventions are not used
```c++
enum class Axis { X, Y, Z};

template<Axis A = Axis::Z, Axis B = Axis::Y, Axis C = Axis::X>
class EulerAngles {
public:
    EulerAngles(int _a, int _b, int _c)
     : a(_a), b(_b), c(_c) { static_assert(A == Axis::Z && B == Axis::Y && C == Axis::Z, "Selected euler angle convention not implemented"); }
     
     int a, b, c;
};

template<>
EulerAngles<Axis::Z, Axis::Y, Axis::X>::EulerAngles(int _a, int _b, int _c) : a(_a), b(_b), c(_c) {}
```
The last part creates a partial template specialization for XYZ without the static_assert. Another way is simply not defining the constructor in the base template, but this will raise a non-descriptive linking error instead.

**Comment by mortenfyhn** [comment]
I guess we are digressing a bit :space_invader: 

I think I'll go with your first suggestion, because we will most likely only need ZYX and possibly a small number of other conventions.

**Comment by mortenfyhn** [comment]
The `conjugate` implementation was wrong, so I've fixed it and added `inverse` and `transpose`. Also I copied the eul->quat code from the matrix library, to allow removing quaternion functionality from the matrix library later.

**Comment by mortenfyhn** [comment]
I'm looking into generalizing the Euler angles implementation now. I still think I'll go for just subclassing an `EulerAngles` base class. If I do that, I don't want to keep the Euler <-> quat conversion in the constructors as they are now, because then adding for instance `EulerAnglesZyz` requires modifying the `Quaternion` class with a new constructor that can convert it. I also think that something like `EulerAnglesZyx eul = quaternionToEuler(quat)` and `Quaternion q = eulerToQuaternion(eul)` is a more obvious interface for conversions than using constructors. However, if I implement the conversion like that, as non-member functions, then I don't know how to 'require' that they are implemented for each existing EulerAngles subclass. It would be nice to find a solution that forces their implementation similar to how pure virtual methods do.

Any good ideas?

**Comment by oysstu** [comment]
To answer your question first. If the function for the conversion does not exist, the compiler will complain. It also seems natural that whoever implements a new convention also creates the conversions. The problem with your suggestion is that quaternion -> Euler is a one-to-many conversion, where the type must somehow be specified since we cannot overload on return type. One way to do this is

```c++
quaternionToEuler(const Quaternion &q, EulerAnglesZyx &eul);
eulerToQuaternion(const EulerAnglesZyx &eul, Quaterion &q);   // To provide an identical interface
```
Another possibility is to use a type parameter without a generic base implementation. This allows us to use a return value, and will not allow usage of non-implemented conversions (compile-time error)
```c++
auto eul = quaternionToEuler<EulerAnglesZyx>(const Quaternion &q);
auto quat = eulerToQuaternion(const EulerAngles &eul);
```
If the conversion is implemented as a function and not a constructor/member function, I still think that functionality should be there, e.g something like `auto eul = quat.toEuler<EulerAnglesZyx>()` and `auto quat = eul.toQuaternion()`. If the function template is used, this amounts to a single function for all conversions. I don't have time to make a proper pull request right now, but I can make a quick mockup of my suggestion if you'd like

**Comment by mortenfyhn** [comment]
To answer your answer first, what I wanted was for the compiler to complain if you've added a new class without all its conversion functionality, even though you don't use it yet. But maybe that's doesn't really matter.

I completely didn't realize that you can't overload on return type. I've never wanted to before, so I've also never been unable to.

Type parameter seems good, and I agree that conversion should be possible also through member functions. I'll try it out and see what feels right.

**Comment by oysstu** [comment]
Something like this should work
```c++
class EulerAngles {};

class EulerAnglesZyx : public EulerAngles {
    public:
    EulerAnglesZyx(double _z, double _y, double _x) :
      z(_z), y(_y), x(_x) {};
    double z, y, x;
};

class Quaternion {
    public:
    Quaternion(double _w, double _x, double _y, double _z) :
      w(_w), x(_x), y(_y), z(_z) {};
      
    double w, x, y, z;
};

template<typename T>
T quaternionToEuler(const Quaternion &q) {
    // Default implementation: compile-time protection against use with invalid types
    EulerAngles *eul = new T();
}

template<>
EulerAnglesZyx quaternionToEuler<EulerAnglesZyx>(const Quaternion &q) {
    double w = q.w, x = q.x, y = q.y, z = q.z;
    double roll  = std::atan2(2*(w*x + y*z), 1 - 2*(x*x + y*y));
    double pitch = std::asin( 2*(w*y - x*z));
    double yaw   = std::atan2(2*(w*z + x*y), 1 - 2*(y*y + z*z));
    return EulerAnglesZyx(roll, pitch, yaw);
}

int main() {
    Quaternion q(1, 1, 1, 1);
    auto eul = quaternionToEuler<EulerAnglesZyx>(q);
    std::cout << eul.z << " " << eul.y << " " << eul.x;
}
```
In c++14, the default implementation can simply be replaced by
```c++
template<typename T, typename = std::enable_if_t<std::is_base_of<EulerAngles, T>::value>>
T quaternionToEuler(const Quaternion &q);
```
On a side note, the geometry module in Eigen has a generic transformation from quaternions to Euler angles ([usage](https://stackoverflow.com/a/43192748)). The implementation is taken from graphic gems IV it seems and cleaned up a bit.

**Comment by mortenfyhn** [comment]
What do you (@oysstu) and the LSTS crew think about this? Do we need to generalize the euler angles, or is it acceptable to merge this PR with `EulerAnglesZyx` as now and optionally generalizing in the future if the need arises?

**Comment by mariacosta** [comment]
Hi mortenfyhn,

First of all, thanks for the effort on this. Regarding the generalization I agree with the input José Braga gave in the past in issue #120.
But since this has been pending for quite some time, and seeing that I don't believe we're using this I'm OK with merging as is if ZYX is the convention you will most likely be using in the foreseeable future. Generalization should be done in the future in case other conventions are needed though.

**Pull request merged**
