### PR TITLE
Fix Visual Studio build

### PR DESCRIPTION
**Pull request by mortend**
When building on Visual Studio, the build will fail saying `regex.h` is missing.

This PR fixes that by adding source code for the regex library, and includes it when building on Visual Studio. See `vendor/libraries/regex/Library.cmake`.

The regex library was copied from libgit2 source code.

### CODE REVIEW

**Comment by krisklau** [comment]
Nice with a fix!

Note that I'm no lawyer, but I am a bit confused if we can copy in an LGPL library like this, without violating the license?

**Comment by mortend** [comment]
I see LGPL libraries and other licensed libraries listed in LICENSE.md, so looks like it's fine. Maybe we should add a section about regex in LICENSE.md...

**Comment by oysstu** [comment]
#141 is related to this pull request

**Comment by pmfg** [comment]
Solved with merge of pull request #156

**Pull request closed without merging**
