### PR TITLE
WIP - Adding option for filtering based on Entity in ProxyPathController

### PR DESCRIPTION
**Pull request by krisklau**
For discussion. 

I would like to extend ProxyPathController to be able to filter by Entity, not just System. Available options: 

1: New class EntityProxyPathController, with same functionality but different filter. 
2: New parameter in ProxyPathController, wich sets the filter (System, Entity, System+Entity)
3: Parse the current list and identify if it's a system or entity

Nr 3 is quickly illustrated in the below commit, which would be a quite user-friendly method IMO. 

Any opinions on best approach?

### CODE REVIEW

**Comment by josebraga** [comment]
I think the issue I have with this PR (and by extension with ProxyPathController itself, which stirred some controversy when it was added) is that it goes against the grain of the core functionality that's been working with DUNE for a long time. Allowing an external system to directly control one system **without supervision** is, to my eyes, an accident waiting to happen - if one problem propagates in one controller, it will spread through the formation (assuming that's your idea as well, at least it's the reason for ProxyPathController).

In my mind, there should be a **task** that supervises the exchange. Whenever it gets new references from an external system (a master, or whatever), it double checks the data to prevent possible propagation of errors, and then, **locally** instantiates the message that will drive the current path controller. This could be done as a Supervisor, or probably better, in the formation Maneuver itself.

I do not know your requirements, and maybe, this is really necessary. If it is, you can change Proxy* as much as possible but, to be honest, I am more driven to delete ProxyPathController than to expand it. Specially since it's not doing anything for a long time, and unnecessary in the master branch.

Regards,
José Braga

**Comment by rbencatel** [comment]
I prefer option 3, with a tweak.

What about changing the current "EstimatedState Filter" parameter definition to the following syntax?
<System>+<System> OR self:<Entity>+<Entity> OR <System>+<System>:<Entity>+<Entity>
That way you know you are never going to get conflicts between "System" and "Entity", if for some reason there are two with the same name.

In this case we should use the following filter constructor:
SourceFilter(Tasks::Task& task, const std::vector<std::string>& source, const std::string& msg_name);
Instead of
SourceFilter(Tasks::Task& task, const bool only_systems, const std::vector<std::string>& source,
                   const std::string& msg_name);

Option 2, might reduce the computation time used by the filter every time it runs.

Here is option 4. The same as option 3, but to maintain the computation time of option 2, change the class SourceFilter, adding a constructor with a flag to indicate that the "source" parameter might be either a 1 field (just systems) or a 2 field (systems:entities) entry. That flag then had to be passed to "defineSystemEntityFilter", to check if the "source" parameter was a 1 field or a 2 field entry.

**Comment by krisklau** [comment]
Hi,

Josebraga: I agree on this issue regarding messages from other systems. The background for this change is in my latest post on the lsts google group, sorry I should have mentioned that. My intent was just to filter based on local entities.

Another point is that we can't really filter on systems+entities, since we don't know the entities of remote systems anyway? 

Rbencatel: I like the notion of prefixing with self:. I'm on my phone now, but isn't there a MessageFilter class more suited in this special case? And ref comment above, without getting entity info from remote system, system+entity might not make sense. 

A fifth option could be to add the option of a local entity filter in PathController, coded as to not filter if no entities specified. (Just to confirm, I only need to filter local entities)

**Comment by josebraga** [comment]
Ok understood. Although if access to ardupilot (or external estimation) is centralized, the switch to produce one or the other could be at the task level (i.e., having always only **one** estimatedstate producer). If you want to produce both at the same time, I guess there's no other option.

We **could** ask for the entity list from another system to get the entities **but** having multiple controllers on a external system controlling the vehicle would be a mess!

**Comment by rbencatel** [comment]
Yes. The systems:entities option for the "EstimatedState Filter" parameter does not make sense in this task.

I think the MessageFilter and the SourceFilter overlap a bit.

I think now the main question is: do you really need the "EstimatedState" to come from 2 different sources?
From what I understand, it is not a requirement. It is just a way to go around the EstimateState translation from the MAVLink messages, correct?

If refactoring the ArduPilot task is not an option for you alone, could you implement a switch method inside that would select the state source (MAVLink, RTK, or a mix), and only output one "EstimatedState"? Or you would rather not change the ArduPilot task?

Another question. If the ProxyPathController was really the solution for your problem, in a vehicle it was going to be permanently setup to only get the "EstimatedState" from the RTK task or would it jump from the RTK to the Ardupilot? This latest possibility could be problematic.

**Comment by krisklau** [comment]
Hi,

True, I do not really need the two sources. I wanted to not introduce to much more logic and states into the ardupilot task, such as timeouts for RTK messages etc. It's convoluted enough as is, but it is definitely the fastest option. 

But moving on with the work on the uav-supervisor branch might be the best option here. I was thinking of adding a set of messages to report and device navsource availability like illustrated here:
https://github.com/krisklau/imc/commit/3830f885ea5edd0668636191e6d0e67ff4e50900

Then either 
1 - Have some logic in the transports/mavlink task that selects source and dispatch EstimatedState
2 - Have transports/mavlink (or today, the ardupilot task) dispatch not EstimatedState, but a new set of messages like EstimatedPos and EstimatedAttitude (or ExternalNavSource, MavlinkState, etc). A supervisor task would then take all available data and dispatch EstimatedState. This would however introduce some delays. 

Any thoughts on this type of approach?

Regarding switching sources run-time; a switch (most likely from RTK -> mavlink due to lack of fix), should be detected by a supervisor, and trigger a new plan as an emergency or waiting maneuver. 

Thanks for all the input :)

**Comment by rbencatel** [comment]
Hi,
I prefer your option 2 with a twist. The Ardupilot task or in future the Transports/MAVlink task should generate ExternalNavSource (I prefer ExternalNavData) messages. Then, a UAVNavigation task should deal with the ExternalNavData and RTKState (or something like that) generating EstimatedStates, and probably a NavState to be used by the supervisor.
Like the sensors handling, the ardupilot interface, and the control should be separate from navigation, I think it should be separate from the monitoring and supervision.

If we go this way, it should be a simpler change to the Ardupilot task (dispatching ExternalNavData instead of EstimatedState). Then you would have to create the navigation task. The supervisor could come last.

**Comment by krisklau** [comment]
Hi,

I like this approach as well. We would introduce a delay though, do you have a rough estimate of the task-to-task dispatch time on average? 

Kristian

**Comment by rbencatel** [comment]
I do not know that delay, but I think that if you define a higher priority to the Transports/MAVlink and the RTK tasks than for the UAVNavigation, those probably will be executed first, allowing the data treatment (from reception to EstimatedState) to be executed on the same execution cycle.

I am unsure how the priorities affect the task execution order, so this might be wrong. José Braga and Ricardo Martins should now this better than me

**Comment by josebraga** [comment]
I am a little bit confused now to be honest.

With or without the new tasks, Kristian, please confirm to me the following:

* The ardupilot would output a state estimation (which we now put in
EstimatedState messages), and a gps fix (which we save in GpsFix)
* You would add a GPS RTK to the system
* You want the possibility to use Ardupilot's state estimation or compute
it yourself (using either GpsFixRtk, Ardupilot's state estimation or
Ardupilot's gps fix)

Is this right ?


2016-02-02 14:15 GMT+00:00 Ricardo Bencatel <notifications@github.com>:

**Comment by krisklau** [comment]
Hi,

Yes, exactly right. 

I did some work in this today, and basically what is seen in this branch is what I want to do: https://github.com/krisklau/dune/tree/pr/feature/external-nav

with the accompanied imc-messages:
https://github.com/LSTS/imc/pull/9

I hope this made it a bit clearer :)

**Comment by josebraga** [comment]
Hi Kristian,

1) I add thought of using a ExternalNavData just as having EstimatedState
as inline message. This would avoid replicating all the fields, but the
end-result is the same. I add though SensorEstimatedState but I do like
your External keyword.

2) About AvailableNavSources, I am not seeing its application. IMO, whether
the sensor data is available and thus, dispatched, or it is not available
and, as a consequence, not dispatched.

3) About NavSources, I think the bitfield could be extended to state the
sensors (or at least the type) used in the state estimation. Then, what you
are calling "Supervisor", which probably I would put it somewhere in
Navigation/UAV, would not only dispatch EstimatedState, but also this new
message stating which sensors were used in the last update. So, instead of
just "interna / external / gps rtk" I would have something like the list

   - pressure sensor
   - ahrs
   - imu
   - lbl
   - usbl
   - gps
   - gps rtk
   - external navigation estimation (e.g: ardupilot's full state)
   - rpm
   - dvl
   - etc etc.

Finally, the values you chose: "INTERNAL / EXTERNAL / GPS RTK" - for me,
internal or external would be full-state solutions, i.e., EstimatedState
type messages, while GpsRrtk would be sensor data (to be used). You added
GPS RTK in there because it could be the actual "full-state" estimation,
just with Gps RTK messages ?

2016-02-03 13:44 GMT+00:00 krisklau <notifications@github.com>:

**Comment by krisklau** [comment]
1) A much better approach, thanks. 

2) Well, for instance for RTK there are different levels of availability. The fix type (fix/float), and wether or not the solution has been in fix for some time. In the commit I made, you can see that a fix-level of Fixed is required for using it as a source, but should be allowed to be in float for a limited time. The message then enables the use of a separate task to monitor this behavior. Alternatively, all this logic could be moved to the navigation task. Slightly more complex navigation task, but maybe a bit cleaner communication layout. 

3) Good point. To add a bit more granularity would be smart. The reason I called it supervisor was that it should be able to change behavior (e.g. abort a plan/change plan) based on current available sensory input. But this could be done by monitoring current used sources sent by a different task I presume.

4) Yes, earlier I had different fields for Attitude and position to reflect this. RTK would only provide position in this case. I would consider RTK as a position-solution for now. This is how it was first: https://github.com/krisklau/imc/commit/3830f885ea5edd0668636191e6d0e67ff4e50900

I am not quite sure of how to go ahead with 3) and 4). We could add more sensors to the mask (and basically removing Internal), but how should it otherwise be reflected that data is not coming from not a FullstateSolution, but a combination of a fullstate solution and a partial (i.e. position)?

**Comment by josebraga** [comment]
2) Understood. I think that although less reliable, data is still data, and
probably a very unreliable GpsRtk fix may be better that alternatives (I am
guessing, I know that's for sure the case for AUVs). The navigation would
have to sort all that out. The GpsFix message also has hdop and hacc
signals that are not very easy to translate to kalman's noise levels.

3) I guess it would be cleaner to have all that separate. A localization
task would output a current estimate, plus few messages:
navigationuncertainty, and navigation sources; A supervisor task could use
that information to trigger behaviors.

4) I guess by setting all the bits. I am think of a scenario where the
system could use everything - gps rtk, the ardupilots state estimate, and
the ardupilots sensor state estimates.. the bitfield would have something
like:

GpsRtk=1,
External=1
Ahrs=1 (although coming from external)..

we could even add even more granularity:

internal ahrs=1
external system ahrs=1
so on..

2016-02-03 14:18 GMT+00:00 krisklau <notifications@github.com>:

**Comment by krisklau** [comment]
2) I see your point. Personally I like the idea of having these functionalities seperate, and the navigation can still chose to do whatever it will with the data, as it still gets the messages. It just removes the settings and code to a separate task for the sake of modularity. But, for the sake of starting small, I could do all that checking in the navigation task for now, and consider the split as a future thing based on needs. 

3) A message with navuncertanty, could that be enumerated or continuous values?

E.g.
msg.pos_type (gps fix level: 2Dfix, 3Dfix, RTK Float, RTK Fix)
msg.pos_uncertainty (some representation of ambiguity. )
msg.vel_type (main source: Integrated Accelerometer, Gps COG, RTK phase)
msg.vel_uncertainty (again, some floating point number)
msg.att_type (ahrs)
msg.att_unc
msg.rotvel_type
msg.rotvel_unc.

etc. Seems like a lot of these fields with be hard to fill (unavailable data) for now though. 

4) Sure! Since ahrs techically only is about attidude, should it be a similar category for position as well (including velocity), or just that just go under gnss or rtk? A point would be to emphasize that an external filter is fusing gps with accelerometer and other available data. 

So, in total, do
internal_ahrs
external_ahrs
external_gnss (location? pos?)
Gnss
GnssRtk
Airspeed
Pressure
etc

**Comment by josebraga** [comment]
3) *NavigationUncertainty* already exists: it expresses an uncertainty
value on different estimatedstate fields (x, y, z, u, v...)

I notice that most of the examples were related with GpsFixRtk - so the
uncertainty in the fix must be stated in the message GpsFixRtk itself.

That's what we do with GpsFix, and without major issues:
Our localization then, depending on the type of GpsFix, may reject or
accept it, while expressing the reason.
Please refer to GpsFixRejection, DvlRejection and LblRangeAcceptance. The
first two are only sent when measurements from GPS and DVL, respectively,
are rejected.
LblRangeAcceptance is sent everytime a LblRange is received by the
localization, to mark if the LblRange was rejected/accepted and why.

Maybe a GpsFixRtkRejection may be required ? Finally, there are 4 bits
available in GpsFixRejection that can be defined.

4) I guess the list should have the current options only. The more complex
ones relate to the "external" from ardupilots, so:

* internal ahrs, external ahrs, internal gps, external gps, gpsrtk,
airspeed, pressure,.... (so on),... and external full state (using another
systems' estimation)


2016-02-03 17:11 GMT+00:00 krisklau <notifications@github.com>:

**Comment by krisklau** [comment]
3) Ah, there is a proper message with variances for that. Nice :) We should be able to fill this data from the EKF running in the newer ardupilot versions as well. 

Also a good approach with GpsFixRtkRejection. The supervisor can then listen for that, in addition of a general timeout for receiving any data. 

4) Ok. I realize that we keep using the word GPS all the time, when we really should be talking about GNSS in general. But I guess this is throughout Dune, so no point doing anything different in this current scenario. In the example you post, external_gps is synonmyous with a position/vel source, on the same level as ahrs is a generic source for attitude and angular rates? I do not know of a term describing a position system in the same way ahrs describes an attitude system. Localization something maybe?

**Comment by josebraga** [comment]
me neither,
but under the law of DUNE, it shall be henceforth known as... the GPS

2016-02-03 17:53 GMT+00:00 krisklau <notifications@github.com>:

**Comment by krisklau** [comment]
Haha :)

PV (Position and Velocity) (system?) is another option.

**Comment by rbencatel** [comment]
You can also try to extend the current GpsFix and GpsFixRejection messages to allow their use for the RTK data and other GNSS systems. It should also include an enumeration to indicate the type of GNSS/DGNSS state being reported. This way the navigation and supervision tasks can handle very similarly all the GNSS/DGNSS cases.

**Comment by krisklau** [comment]
rbencatel: I agree this could be a good thing, but I think that is a future thing for now. Easier to not change existing stuff to much until I'm sure of our requirements. 

I'm thinking this for the mask:

    <value id="0x00000001" name="Internal Fullstate" abbrev="INTERNAL_FULLSTATE"/>
    <value id="0x00000002" name="Internal Attitide Heading Reference System" abbrev="INTERNAL_AHRS"/>
    <value id="0x00000004" name="Internal Position Reference System" abbrev="INTERNAL_POSREF"/>
    <value id="0x00000008" name="External Fullstate" abbrev="EXTERNAL_FULLSTATE"/>
    <value id="0x00000010" name="External Attitide Heading Reference System" abbrev="EXTERNAL_AHRS"/>
    <value id="0x00000020" name="External Position Reference System" abbrev="EXTERNAL_POSREF"/>
    <value id="0x00000040" name="GNSS" abbrev="GNSS"/>
    <value id="0x00000080" name="GNSS RTK" abbrev="GNSS_RTK"/>
    <value id="0x00000100" name="Pressure" abbrev="PRESSURE"/>
    <value id="0x00000200" name="Airspeed" abbrev="AIRSPEED"/>
    <value id="0x00000400" name="Altimeter" abbrev="ALTIMETER"/>
    <value id="0x00000800" name="LBL" abbrev="LBL"/>
    <value id="0x00001000" name="USBL" abbrev="USBL"/>
    etc

Thoughts?

**Comment by krisklau** [comment]
Moved discussion here: https://github.com/LSTS/dune/pull/50

**Pull request closed without merging**
