### PR TITLE
Feature/wifi rssi

### PR DESCRIPTION
**Pull request by zepinto**
This task uses SSH to obtain Wi-Fi link quality (RSSI) from access point.

### CODE REVIEW

**Comment by rasmartins** [comment]
Can we call this AirOS instead of WifiRSSI ?

**Comment by zepinto** [comment]
I didn't call it that because it works not only for AirOS but also for (local) wi-fi dongles, however I have no problem if it gets renamed.

**Comment by rasmartins** [comment]
I'm fine with the name. Will merge this PR once it's proper documented.

**Comment by zepinto** [comment]
Added documentation as required.

**Pull request merged**
